#!/usr/bin/env bash
# Cursor theme manager for the Quickshell settings UI.
#   list [size]          -> JSON array of installed cursor themes (+ preview png)
#   apply <theme> [size] -> apply live everywhere and persist for next login
#   import               -> pick a downloaded archive and install it
#
# Persistence avoids config/env.conf on purpose: settings_watcher.sh regenerates
# that file from a template, so cursor env lives in its own sourced cursor.conf.

set -euo pipefail

SCRIPT="$(cd "$(dirname "$0")" && pwd)"
RENDER="$SCRIPT/render_cursor.py"
HYPR_DIR="$HOME/.config/hypr"
CACHE="$HOME/.cache/hypr-cursor/previews"
SEARCH_DIRS=("$HOME/.icons" "$HOME/.local/share/icons" "/usr/share/icons")

resolve_cursor_file() {
    # echoes a real (dereferenced) cursor file for a theme dir, if any
    local themedir="$1"
    local n src
    for n in default left_ptr arrow; do
        src="$(readlink -f "$themedir/cursors/$n" 2>/dev/null || true)"
        [ -f "$src" ] && { echo "$src"; return 0; }
    done
    # fall back to the first regular file in cursors/
    src="$(find "$themedir/cursors" -maxdepth 1 -type f 2>/dev/null | head -1 || true)"
    [ -n "$src" ] && { echo "$src"; return 0; }
    return 1
}

cmd_list() {
    local size="${1:-48}"
    mkdir -p "$CACHE"
    local -A seen=()
    {
        local base theme name src pv
        for base in "${SEARCH_DIRS[@]}"; do
            [ -d "$base" ] || continue
            for theme in "$base"/*/; do
                [ -d "${theme}cursors" ] || continue
                name="$(basename "$theme")"
                [ -n "${seen[$name]:-}" ] && continue
                seen[$name]=1
                pv=""
                if src="$(resolve_cursor_file "${theme%/}")"; then
                    pv="$CACHE/${name}.png"
                    if [ ! -f "$pv" ] || [ "$src" -nt "$pv" ]; then
                        python3 "$RENDER" "$src" "$pv" "$size" 2>/dev/null || pv=""
                    fi
                fi
                jq -nc --arg n "$name" --arg p "${theme%/}" --arg pv "$pv" \
                    '{name:$n, path:$p, preview:$pv}'
            done
        done
    } | jq -sc 'sort_by(.name | ascii_downcase)'
}

cmd_apply() {
    local theme="$1" size="${2:-24}"
    [ -z "$theme" ] && { echo "apply: theme required" >&2; exit 1; }

    # GTK / GNOME apps
    gsettings set org.gnome.desktop.interface cursor-theme "$theme" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface cursor-size "$size" 2>/dev/null || true

    # XWayland and legacy X apps
    mkdir -p "$HOME/.icons/default"
    printf '[Icon Theme]\nInherits=%s\n' "$theme" > "$HOME/.icons/default/index.theme"

    # Hyprland live session
    hyprctl setcursor "$theme" "$size" >/dev/null 2>&1 || true
    hyprctl setenv XCURSOR_THEME "$theme" >/dev/null 2>&1 || true
    hyprctl setenv XCURSOR_SIZE "$size" >/dev/null 2>&1 || true

    # Persist for next login in a dedicated file (NOT env.conf, which is templated)
    local cursor_conf="$HYPR_DIR/config/cursor.conf"
    {
        echo "# AUTOGENERATED by cursor_manager.sh"
        echo "env = XCURSOR_THEME,$theme"
        echo "env = XCURSOR_SIZE,$size"
    } > "$cursor_conf"

    # Make sure hyprland.conf sources it (idempotent)
    local hypr_conf="$HYPR_DIR/hyprland.conf"
    if [ -f "$hypr_conf" ] && ! grep -q 'config/cursor.conf' "$hypr_conf"; then
        printf '\nsource = ~/.config/hypr/config/cursor.conf\n' >> "$hypr_conf"
    fi

    command -v notify-send >/dev/null && notify-send "Cursor" "Applied $theme ($size px)" || true
}

cmd_import() {
    local file dest tmp themedir name curdir found=0
    file="$(zenity --file-selection \
        --title="Select a downloaded cursor archive" \
        --file-filter="Cursor archives | *.tar.gz *.tgz *.tar.xz *.tar.bz2 *.tar.zst *.zip" \
        --file-filter="All files | *" 2>/dev/null)" || exit 0
    [ -z "$file" ] && exit 0

    dest="$HOME/.local/share/icons"
    mkdir -p "$dest"
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT

    case "$file" in
        *.zip)              unzip -q "$file" -d "$tmp" ;;
        *.tar.gz|*.tgz)     tar -xzf "$file" -C "$tmp" ;;
        *.tar.xz)           tar -xJf "$file" -C "$tmp" ;;
        *.tar.bz2)          tar -xjf "$file" -C "$tmp" ;;
        *.tar.zst)          tar --zstd -xf "$file" -C "$tmp" ;;
        *) notify-send "Cursor" "Unsupported file type"; exit 1 ;;
    esac

    while IFS= read -r curdir; do
        themedir="$(dirname "$curdir")"
        name="$(basename "$themedir")"
        rm -rf "${dest:?}/$name"
        cp -r "$themedir" "$dest/$name"
        found=$((found + 1))
    done < <(find "$tmp" -type d -name cursors)

    if [ "$found" -gt 0 ]; then
        notify-send "Cursor" "Imported $found theme(s) to ~/.local/share/icons"
    else
        notify-send "Cursor" "No valid cursor theme found in that archive"
        exit 1
    fi
}

case "${1:-}" in
    list)   shift; cmd_list "$@" ;;
    apply)  shift; cmd_apply "$@" ;;
    import) shift; cmd_import "$@" ;;
    *) echo "usage: $0 {list [size]|apply <theme> [size]|import}" >&2; exit 2 ;;
esac
